<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flh.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminModifyHistory
    {
        public long ophID { get; set; }
        public long adminUid { get; set; }
        public string opContent { get; set; }
        public System.DateTime created { get; set; }
        public long operatorUid { get; set; }
    }
}
=======

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flh.Business.Data
{

using System;
    using System.Collections.Generic;
    
public partial class AdminModifyHistory
{

    public long ophID { get; set; }

    public long adminUid { get; set; }

    public string opContent { get; set; }

    public System.DateTime created { get; set; }

    public long operatorUid { get; set; }

}

}
>>>>>>> 8fd1cef484ddc46e940c7ae51aa784378a865dc1
