//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flh.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long pid { get; set; }
        public string name { get; set; }
        public string enName { get; set; }
        public string description { get; set; }
        public string enDescription { get; set; }
        public string size { get; set; }
        public string enSize { get; set; }
        public string color { get; set; }
        public string enColor { get; set; }
        public string material { get; set; }
        public string enMaterial { get; set; }
        public string technique { get; set; }
        public string enTechnique { get; set; }
        public int minQuantity { get; set; }
        public int deliveryDay { get; set; }
        public string keywords { get; set; }
        public string enKeywords { get; set; }
        public decimal unitPrice { get; set; }
        public string imagePath { get; set; }
        public string classNo { get; set; }
        public int sortNo { get; set; }
        public long createUid { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public bool enabled { get; set; }
        public Nullable<long> updater { get; set; }
        public Nullable<int> viewCount { get; set; }
    }
}
