//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flh.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.LoginHistory = new HashSet<LoginHistory>();
        }
    
        public long uid { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string pwd { get; set; }
        public string name { get; set; }
        public string company { get; set; }
        public string area_no { get; set; }
        public string address { get; set; }
        public Flh.Business.Users.EmployeesCountRanges employees_count_type { get; set; }
        public string industry_no { get; set; }
        public bool is_purchaser { get; set; }
        public bool neet_invoice { get; set; }
        public string tel { get; set; }
        public System.DateTime register_date { get; set; }
        public System.DateTime last_login_date { get; set; }
        public bool enabled { get; set; }
        public string enabled_memo { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ICollection<LoginHistory> LoginHistory { get; set; }
    }
}
